.PHONY: help build clean deploy-scraper deploy-web-prod db-bootstrap db-migrate-local db-migrate-prod db-reset db-up db-down dev-scraper dev-web format gen-key install install-scraper install-web inspect-scraper lint lint-ci lint-scraper lint-web lint-web-fix open-trending-details recompute-scores-once scrape-sample scrape-trending-300 scrape-visible security security-scraper security-web tail-logs test test-scraper test-web tune-ranking-weights venv

# Default target
help:
	@echo "Nextdoor Podcast Discovery Platform"
	@echo ""
	@echo "Usage: make <target>"
	@echo ""
	@echo "Setup:"
	@echo "  venv             Create Python virtual environment"
	@echo "  install          Install all dependencies (requires venv activation)"
	@echo "  install-scraper  Install scraper dependencies only"
	@echo "  install-web      Install web dependencies only"
	@echo ""
	@echo "Database:"
	@echo "  db-up            Start local Postgres database"
	@echo "  db-down          Stop local Postgres database"
	@echo "  db-reset         Reset local database (delete all data)"
	@echo "  db-bootstrap     Generate database/bootstrap.sql (all migrations in one file)"
	@echo "  db-migrate-local Run migrations on local database"
	@echo "  db-migrate-prod  Show how to run migrations on Supabase"
	@echo ""
	@echo "Development:"
	@echo "  build            Build Next.js for production"
	@echo "  dev-scraper      Run scraper in dry-run mode"
	@echo "  dev-web          Start Next.js dev server"
	@echo "  scrape-sample    Scrape 25 posts from trending with scoring and embeddings (full pipeline)"
	@echo "  scrape-trending-300  Scrape, score, and embed 300 trending posts (long run; use PYTHONUNBUFFERED=1 and tee for logs)"
	@echo "  scrape-visible   Run scraper with browser visible (5 trending posts; use to watch Nextdoor)"
	@echo "  inspect-scraper  Run scraper in inspect mode (browser pauses for DOM inspection)"
	@echo "  open-trending-details  Open trending tab, click first post to details view, then pause"
	@echo "  tune-ranking-weights   Tune active weight_configs (ARGS='--examples-file PATH'; optional --no-novelty for prod-aligned objective; scraper/.env)"
	@echo "  recompute-scores-once  Process one pending recompute_final_scores job (local worker; scraper/.env; queue job via admin API first)"
	@echo ""
	@echo "Quality:"
	@echo "  lint             Run linters (scraper + web, check only)"
	@echo "  lint-ci          Run linters with ESLint --fix for web (use in CI)"
	@echo "  lint-scraper     Run Python linters (ruff, mypy)"
	@echo "  lint-web         Run TypeScript linter (eslint)"
	@echo "  format           Format all code"
	@echo ""
	@echo "Security:"
	@echo "  security         Run all security scans"
	@echo "  security-scraper Run Python security scans (bandit, pip-audit)"
	@echo "  security-web     Run TypeScript security scan (npm audit)"
	@echo ""
	@echo "Testing:"
	@echo "  test             Run all tests"
	@echo "  test-scraper     Run scraper tests only"
	@echo "  test-web         Run web tests only"
	@echo ""
	@echo "Deploy:"
	@echo "  deploy-scraper   Deploy scraper to server (set DEPLOY_HOST; optional FEED=recent|trending)"
	@echo "  deploy-web-prod Merge main into release and push (promotes web to production)"
	@echo "  tail-logs       Tail scraper logs on server (set DEPLOY_HOST; optional ARGS=\"-n 500\")"
	@echo "  (Deploy web to dev: push to main, e.g. git push origin main)"
	@echo ""
	@echo "Utilities:"
	@echo "  gen-key          Generate encryption key for sessions"
	@echo "  clean            Remove generated files and caches"

# Create virtual environment
venv:
	python3 -m venv .venv
	@echo ""
	@echo "Virtual environment created. Activate with:"
	@echo "  source .venv/bin/activate"

# Database
db-up:
	docker-compose up -d db
	@echo "Database running at localhost:5432"
	@echo "  User: nextdoor"
	@echo "  Password: localdev"
	@echo "  Database: nextdoor"

db-down:
	docker-compose down

db-reset:
	docker-compose down -v
	docker-compose up -d db
	@echo "Database reset complete. All data deleted."
	@echo "Migrations will run automatically on startup."

db-bootstrap:
	@echo "Generating database/bootstrap.sql (all migrations in order)..."
	@(echo "-- Generated by 'make db-bootstrap'. Source: database/migrations/ (all files in sorted order). Do not edit by hand."; echo ""; for f in $$(ls database/migrations/*.sql | sort -V); do cat "$$f"; done) > database/bootstrap.sql
	@echo "Done. Run database/bootstrap.sql once in Supabase SQL Editor for a new project."
	@echo "After adding a new migration, run 'make db-bootstrap' again and commit the updated file."

db-migrate-local:
	@echo "Running migrations on local database..."
	@ls database/migrations/*.sql | sort -V | xargs cat | docker-compose exec -T db psql -U nextdoor -d nextdoor
	@echo ""
	@echo "Done! Tables created."

db-migrate-prod:
	@echo "=============================================="
	@echo "  SUPABASE MIGRATION INSTRUCTIONS"
	@echo "=============================================="
	@echo ""
	@echo "New project (no schema yet): Run database/bootstrap.sql once in SQL Editor."
	@echo "Existing project: Run only migration files not yet applied, in numeric order."
	@echo ""
	@echo "See docs/SUPABASE_MIGRATIONS.md for details."
	@echo ""
	@echo "=============================================="

# Install dependencies
install: install-scraper install-web
	@echo ""
	@echo "All dependencies installed!"

install-scraper:
	@if [ -z "$$VIRTUAL_ENV" ]; then \
		echo "Warning: No virtual environment detected."; \
		echo "Run 'make venv && source .venv/bin/activate' first."; \
		exit 1; \
	fi
	cd scraper && pip install -r requirements.txt -r requirements-dev.txt
	cd scraper && playwright install chromium

install-web:
	cd web && npm install --legacy-peer-deps

# Development
build:
	cd web && npm run build

dev-scraper:
	cd scraper && python -m src.main --dry-run

scrape-sample:
	cd scraper && python -m src.main --feed-type trending --max-posts 25

# Visible browser: open Chromium so you can watch the scraper on Nextdoor (small run).
scrape-visible:
	cd scraper && python -m src.main --feed-type trending --max-posts 5 --visible

# Long run: 300 trending posts (scrape + score + embed). caffeinate keeps Mac/display
# awake so browser does not freeze when screensaver or sleep would kick in.
# Capture logs: PYTHONUNBUFFERED=1 make scrape-trending-300 2>&1 | tee scrape.log
scrape-trending-300:
	cd scraper && caffeinate -dis python -m src.main --feed-type trending --max-posts 300

inspect-scraper:
	cd scraper && python -m src.main --inspect

open-trending-details:
	cd scraper && python -m src.main --open-trending-details

# Example: make tune-ranking-weights ARGS='--examples-file ./my-posts.txt --no-novelty --apply'
tune-ranking-weights:
	cd scraper && ../.venv/bin/python -m src.tune_ranking_weights $(ARGS)

# After POST /api/admin/recompute-scores (pending job in background_jobs): run worker once locally
recompute-scores-once:
	cd scraper && ../.venv/bin/python -m src.worker --job-type recompute_final_scores --once

dev-web:
	cd web && npm run dev

# Linting
lint: lint-scraper lint-web

# For CI: same as lint but web runs eslint --fix so fixable issues are fixed in the runner.
lint-ci: lint-scraper lint-web-fix

lint-scraper:
	cd scraper && ../.venv/bin/ruff format src/
	cd scraper && ../.venv/bin/ruff format --check src/
	cd scraper && ../.venv/bin/ruff check src/
	cd scraper && ../.venv/bin/mypy src/

lint-web:
	cd web && npm run lint

lint-web-fix:
	cd web && npm run lint:fix

format:
	cd scraper && ../.venv/bin/ruff format src/
	cd scraper && ../.venv/bin/ruff check --fix src/

# Security
security: security-scraper security-web

security-scraper:
	@echo "Running bandit (Python security linter)..."
	.venv/bin/bandit -r scraper/src/ -ll
	@echo ""
	@echo "Running pip-audit (dependency vulnerabilities)..."
	@echo "Ignoring CVE-2026-4539 (pygments ReDoS): no fixed PyPI release after 2.19.2 yet (GHSA-5239-wwwm-4pmq)."
	.venv/bin/pip-audit --ignore-vuln CVE-2026-4539

security-web:
	@echo "Running npm audit (dependency vulnerabilities)..."
	cd web && npm audit

# Testing
test: test-scraper test-web

test-scraper:
	cd scraper && ../.venv/bin/pytest -v

test-web:
	cd web && npm test

# Deploy
deploy-scraper:
	@if [ -z "$$DEPLOY_HOST" ]; then \
		echo "Error: set DEPLOY_HOST (e.g. make deploy-scraper DEPLOY_HOST=user@host)"; \
		exit 1; \
	fi
	./scripts/deploy-to-server.sh $(FEED)

deploy-web-prod:
	@if git status --porcelain | grep -q .; then \
		echo "Error: uncommitted changes; commit or stash first"; \
		exit 1; \
	fi
	git checkout release && \
	git pull origin release && \
	git merge main --no-edit && \
	git push origin release && \
	git checkout main

tail-logs:
	@if [ -z "$$DEPLOY_HOST" ]; then \
		echo "Error: set DEPLOY_HOST (e.g. make tail-logs DEPLOY_HOST=user@host)"; \
		exit 1; \
	fi
	./scripts/tail-logs.sh $(ARGS)

# Utilities
gen-key:
	python scripts/generate-encryption-key.py

clean:
	find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
	find . -type d -name ".pytest_cache" -exec rm -rf {} + 2>/dev/null || true
	find . -type d -name "node_modules" -exec rm -rf {} + 2>/dev/null || true
	find . -type d -name ".next" -exec rm -rf {} + 2>/dev/null || true
	find . -type f -name "*.pyc" -delete 2>/dev/null || true
